return {
  -- {
  --   'folke/noice.nvim',
  --   event = 'VeryLazy',
  --   opts = {
  --     messages = {
  --       enabled = true,
  --       -- view = 'cmdline',
  --     },
  --     routes = {
  --       view = 'messages',
  --       filter = { event = 'lsp', { find = 'Starting Java Language Server' } },
  --       opts = { skip = true },
  --     },
  --   },
  --   dependencies = {
  --     -- if you lazy-load any plugin below, make sure to add proper `module="..."` entries
  --     'MunifTanjim/nui.nvim',
  --     -- OPTIONAL:
  --     --   `nvim-notify` is only needed, if you want to use the notification view.
  --     --   If not available, we use `mini` as the fallback
  --     'rcarriga/nvim-notify',
  --   },
  -- },
}
